[target.x86_64-unknown-linux-gnu]
rustflags = [
	"-C", "panic=abort",
	"-C", "target-cpu=native -C target-feature=+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+avx,+avx2,+fma,+popcnt",
	"-C", "target-cpu=native",
	"-C", "debuginfo=0"
]
